compatibility_date = "2024-04-19"
name = "placeholder_api"

[vars]
UPSTASH_REDIS_REST_URL= "https://us1-renewing-fly-38451.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AZYzASQgNDNiYjdjMzgtZDQ5Yi00OGM1LWE4M2EtZTM3ZTM5YjQzMDkzNDU2OWQwOTU1OTFmNDk3MGI0OWJjMGU4ZGVhMGU5ODk="